TrikProjekt/Controllers/Case2Controller.cs
namespace TrikProjekt56.Controllers
{
    [Authorize]
    public class Case2Controller : Controller
    {
        private void AddViewbags()
        {
            ViewBag.Categories = GetCategories();
            ViewBag.Genders = GetGenders();
            ViewBag.Locations = GetLocations();
            ViewBag.Ages = GetAges();
            ViewBag.Hairs = GetHairs();
            ViewBag.Religions = GetReligions();
            ViewBag.Educations = GetEducations();
            ViewBag.Heights = GetHeights();
            ViewBag.Weights = GetWeights();
        }

        private readonly ICase _repo;
        private readonly ICategory _categoryrepo;
        private readonly ILocation _locationrepo;
        private readonly IAge _agerepo;
        private readonly IHair _hairrepo;
        private readonly IGender _genderrepo;
        private readonly IReligion _religionrepo;
        private readonly IEducation _educationrepo;
        private readonly IWeight _weightrepo;
        private readonly IHeight _heightrepo;

        public Case2Controller(ICase repo, ICategory categoryrepo, ILocation locationrepo, IAge agerepo, IHair hairrepo, IGender genderrepo, IReligion religionrepo, IEducation educationrepo, IWeight weightrepo, IHeight heightrepo)
        {
            _repo = repo;
            _categoryrepo = categoryrepo;
            _locationrepo = locationrepo;
            _agerepo = agerepo;
            _hairrepo = hairrepo;
            _genderrepo = genderrepo;
            _religionrepo = religionrepo;
            _educationrepo = educationrepo;
            _heightrepo = heightrepo;
            _weightrepo = weightrepo;
        }
        public IActionResult Index(string sortExpression = "", string SearchText = "", int pageIndex = 1, int pageSize = 25)
        {
            SortModel sortModel = new SortModel();
            sortModel.AddColumn("Code");
            sortModel.AddColumn("name");
            sortModel.ApplySort(sortExpression);
            ViewData["sortModel"] = sortModel;
            ViewBag.SearchText = SearchText;
            Pagination<Case> items = _repo.GetItems(sortModel.SortedProperty, sortModel.SortedOrder, SearchText, pageIndex, pageSize);
            var site = new SiteModel(items.TotalRecords, pageIndex, pageSize);
            site.SortExpression = sortExpression;
            this.ViewBag.Site = site;
            TempData["CurrentPage"] = pageIndex;
            TempData["PageSize"] = pageSize;
            return View(items);
        }

        public IActionResult Create()
        {
            Case item = new Case();
            AddViewbags();
            TempData.Keep();
            return View(item);
        }

        [HttpPost]
        public IActionResult Create(Case item)
        {
            AddViewbags();
            TempData.Keep();
            bool myBool = false;
            string errMessage = "";
            int pageSize = 5;
            if (TempData["PageSize"] != null)
            {
                pageSize = (int)TempData["PageSize"];
            }
            int currentPage = 1;
            if (TempData["CurrentPage"] != null)
            {
                currentPage = (int)TempData["CurrentPage"];
            }
            try
            {
                if (item.Name.Length < 3 || item.Name == null)
                    errMessage = "Name must be at least 3 characters";
                if (_repo.IsCodeExisting(item.Code) == true)
                    errMessage = "Code " + item.Code + " already exists in database";
                if (_repo.IsExisting(item.Name) == true)
                    errMessage = "Name " + item.Name + " already exists in database";
                if (errMessage == "")
                {
                    item = _repo.Create(item);
                    myBool = true;
                }
            }
            catch (Exception exc)
            {
                errMessage += " " + exc.Message;
            }
            if (myBool == false)
            {
                TempData["ErrorMessage"] = errMessage;
                ModelState.AddModelError("", errMessage);
                return View(item);
            }
            else
            {
                TempData["SuccessMessage"] = item.Name + " created successfully!";
                return RedirectToAction(nameof(Index), new { pageIndex = currentPage, pageSize = pageSize });
            }
        }

        public IActionResult Details(string id)
        {
            Case item = _repo.GetItem(id);
            AddViewbags();
            TempData.Keep();
            return View(item);
        }
        public IActionResult Edit(string id)
        {
            Case item = _repo.GetItem(id);
            AddViewbags();
            TempData.Keep();
            return View(item);
        }


        [HttpPost]
        public IActionResult Edit(Case item)
        {
            AddViewbags();
            bool myBool = false;
            string errMessage = "";
            try
            {
                if (item.Name.Length < 3 || item.Name == null)
                    errMessage = "Name must be at least 3 characters";
                if (_repo.IsExisting(item.Name, item.Code) == true)
                    errMessage += item.Name + " already exists in database";
                if (errMessage == "")
                {
                    item = _repo.Edit(item);
                    TempData["SuccessMessage"] = item.Name + " saved successfully!";
                    myBool = true;
                }
            }
            catch (Exception exc)
            {
                errMessage += " " + exc.Message;
            }
            int currentPage = 1;
            if (TempData["CurrentPage"] != null)
            {
                currentPage = (int)TempData["CurrentPage"];
            }
            int pageSize = 5;
            if (TempData["PageSize"] != null)
            {
                pageSize = (int)TempData["PageSize"];
            }
            if (myBool == false)
            {
                TempData["ErrorMessage"] = errMessage;
                ModelState.AddModelError("", errMessage);
                return View(item);
            }
            else
            {
                return RedirectToAction(nameof(Index), new { pageIndex = currentPage, pageSize = pageSize });
            }
        }

        public IActionResult Delete(string id)
        {
            Case item = _repo.GetItem(id);
            TempData.Keep();
            return View(item);
        }

        [HttpPost]
        public IActionResult Delete(Case item)
        {
            try
            {
                item = _repo.Delete(item);
            }
            catch (Exception exc)
            {
                string errMessage = exc.Message;
                TempData["ErrorMessage"] = errMessage;
                ModelState.AddModelError("", errMessage);
                return View(item);
            }
            int currentPage = 1;
            if (TempData["CurrentPage"] != null)
            {
                currentPage = (int)TempData["CurrentPage"];
            }
            int pageSize = 5;
            if (TempData["PageSize"] != null)
            {
                pageSize = (int)TempData["PageSize"];
            }
            TempData["SuccessMessage"] = item.Name + " deleted successfully!";
            return RedirectToAction(nameof(Index), new { pageIndex = currentPage, pageSize = pageSize });
        }
        private List<SelectListItem> GetCategories()
        {
            var IsUnits = new List<SelectListItem>();
            Pagination<Category> categories = _categoryrepo.GetItems("Name", SortOrder.Ascending, "", 1, 1000);
            IsUnits = categories.Select(u => new SelectListItem()
            {
                Value = u.Id.ToString(),
                Text = u.Name
            }).ToList();
            var defaultitem = new SelectListItem()
            {
                Value = "",
                Text = "Select Item"
            };
            IsUnits.Insert(0, defaultitem);
            return IsUnits;
        }
        private List<SelectListItem> GetLocations()
        {
            var IsUnits = new List<SelectListItem>();
            Pagination<Location> items = _locationrepo.GetItems("Name", SortOrder.Ascending, "", 1, 1000);
            IsUnits = items.Select(u => new SelectListItem()
            {
                Value = u.Id.ToString(),
                Text = u.Name
            }).ToList();
            var defaultitem = new SelectListItem()
            {
                Value = "",
                Text = "Select location"
            };
            IsUnits.Insert(0, defaultitem);
            return IsUnits;
        }
        private List<SelectListItem> GetAges()
        {
            var IsUnits = new List<SelectListItem>();
            Pagination<Age> items = _agerepo.GetItems("Name", SortOrder.Ascending, "", 1, 1000);
            IsUnits = items.Select(u => new SelectListItem()
            {
                Value = u.Id.ToString(),
                Text = u.Name
            }).ToList();
            var defaultitem = new SelectListItem()
            {
                Value = "",
                Text = "Select age"
            };
            IsUnits.Insert(0, defaultitem);
            return IsUnits;
        }
        private List<SelectListItem> GetHairs()
        {
            var IsUnits = new List<SelectListItem>();
            Pagination<Hair> items = _hairrepo.GetItems("Name", SortOrder.Ascending, "", 1, 1000);
            IsUnits = items.Select(u => new SelectListItem()
            {
                Value = u.Id.ToString(),
                Text = u.Name
            }).ToList();
            var defaultitem = new SelectListItem()
            {
                Value = "",
                Text = "Select hair"
            };
            IsUnits.Insert(0, defaultitem);
            return IsUnits;
        }
        private List<SelectListItem> GetGenders()
        {

TrikProjekt/Views/Case2/Create.cshtml
@model TrikProjekt56.Models.Case

@{
    ViewData["Title"] = "Create";
}

<div class="row Index">
    <div>
        <div class="card-header cardHeader text-uppercase text-center">
            Create new case
        </div>
        <form asp-action="Create">
            <div class="col">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="row">
                    <div class="form-group col-6">
                        <label asp-for="Code" class="control-label"></label>
                        <input asp-for="Code" class="form-control" />
                        <span asp-validation-for="Code" class="text-danger"></span>
                    </div>
                    <div class="form-group col-6">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                     <div class="form-group col-6">
                        <label asp-for="StartDate" class="control-label"></label>
                        <input asp-for="StartDate" class="form-control" />
                        <span asp-validation-for="StartDate" class="text-danger"></span>
                    </div>
                    <div class="form-group col-6">
                        <label asp-for="CategoryId" class="control-label"></label>
                        <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.Categories"></select>
                        <span asp-validation-for="CategoryId" class="text-danger"></span>
                    </div>
                    <div class="form-group col-6">
                        <label asp-for="LocationId" class="control-label"></label>
                        <select asp-for="LocationId" class="form-control" asp-items="ViewBag.Locations"></select>
                        <span asp-validation-for="LocationId" class="text-danger"></span>
                    </div>
                    <div class="form-group col-6">
                        <label asp-for="AgeId" class="control-label"></label>
                        <select asp-for="AgeId" class="form-control" asp-items="ViewBag.Ages"></select>
                        <span asp-validation-for="AgeId" class="text-danger"></span>
                    </div>
                    <div class="form-group col-6">
                        <label asp-for="HairId" class="control-label"></label>
                        <select asp-for="HairId" class="form-control" asp-items="ViewBag.Hairs"></select>
                        <span asp-validation-for="HairId" class="text-danger"></span>
                    </div>
                    <div class="form-group col-6">
                        <label asp-for="GenderId" class="control-label"></label>
                        <select asp-for="GenderId" class="form-control" asp-items="ViewBag.Genders"></select>
                        <span asp-validation-for="GenderId" class="text-danger"></span>
                    </div>
                    <div class="form-group col-6">
                        <label asp-for="ReligionId" class="control-label"></label>
                        <select asp-for="ReligionId" class="form-control" asp-items="ViewBag.Religions"></select>
                        <span asp-validation-for="ReligionId" class="text-danger"></span>
                    </div>
                    <div class="form-group col-6">
                        <label asp-for="EducationId" class="control-label"></label>
                        <select asp-for="EducationId" class="form-control" asp-items="ViewBag.Educations"></select>
                        <span asp-validation-for="EducationId" class="text-danger"></span>
                    </div>
                    <div class="form-group col-6">
                        <label asp-for="HeightId" class="control-label"></label>
                        <select asp-for="HeightId" class="form-control" asp-items="ViewBag.Heights"></select>
                        <span asp-validation-for="HeightId" class="text-danger"></span>
                    </div>
                    <div class="form-group col-6">
                        <label asp-for="WeightId" class="control-label"></label>
                        <select asp-for="WeightId" class="form-control" asp-items="ViewBag.Weights"></select>
                        <span asp-validation-for="WeightId" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="form-group btn-group col-12 mt-1">
                <div class="col-4 mt-1">
                    <input type="submit" value="Create" asp-route-pageSize="@TempData.Peek("PageSize")" asp-route-pageSize="@TempData.Peek("PageSize")" asp-route-pageIndex="@TempData.Peek("CurrentPage")" class="btn btn-primary btn-block" />
                </div>
                <div class="col-4 mt-1">
                    <a class="btn btn-secondary btn-block" asp-action="Index" asp-route-pageSize="@TempData.Peek("PageSize")" asp-route-pageIndex="@TempData.Peek("CurrentPage")">Back</a>
                </div>
                <div class="col-4 form-check mt-2">
                        <input asp-for="isClosed" style="width:25px; height:25 px;" />
                        <label class="font-weight-bold h5">@Html.DisplayNameFor(model => model.isClosed)</label>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationPartial");}
}

TrikProjekt/Views/Case2/Delete.cshtml
@model TrikProjekt56.Models.Case

@{
    ViewData["Title"] = "Delete";
}

<div class="row">
    <div style="width:100%;">
        <div class="card-header cardHeader text-uppercase text-center">
            Delete case
        </div>
        <form asp-action="Delete">
            <div class="col">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="row">
                    <div class="form-group col-6">
                        <label asp-for="Code" class="control-label"></label>
                        <input asp-for="Code" class="form-control" readonly />
                    </div>
                    <div class="form-group col-6">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" readonly />
                    </div>
                    <div class="form-group col-6">
                        <label asp-for="StartDate" class="control-label"></label>
                        <input asp-for="StartDate" class="form-control" readonly />
                    </div>
                    <div class="form-group col-6">
                            <label class="form-check-label">@Html.DisplayNameFor(model => model.isClosed)</label>
                            <br>
                            <input type="checkbox" class="form-check-input mt-2" style="margin-left:0px !important; height:35px !important;" asp-for="isClosed" disabled/>
                    </div>
                </div>
            </div>
            <div class="form-group btn-group col-12 mt-1">
                <div class="col-4 mt-1">
                    <input type="submit" value="Delete" asp-route-pageSize="@TempData.Peek("PageSize")" asp-route-pageIndex="@TempData.Peek("CurrentPage")" class="btn btn-primary btn-block" />
                </div>
                <div class="col-4 mt-1">
                    <a class="btn btn-secondary btn-block" asp-action="Index" asp-route-pageSize="@TempData.Peek("PageSize")" asp-route-pageSize="@TempData.Peek("PageSize")" asp-route-pageIndex="@TempData.Peek("CurrentPage")">Back</a>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationPartial");}
}

TrikProjekt/Views/Case2/Details.cshtml
@model TrikProjekt56.Models.Case
@{
    ViewData["Title"] = "Details";
}

<div class="row Index">
    <div>
        <div class="card-header cardHeader text-uppercase text-center">
            Details of case
        </div>
        <form>
            <div class="col">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="row">
                    <div class="form-group col-6">
                        <label asp-for="Code" class="control-label"></label>
                        <input asp-for="Code" class="form-control" readonly />
                    </div>
                    <div class="form-group col-6">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" readonly />
                    </div>
                     <div class="form-group col-6">
                        <label asp-for="StartDate" class="control-label"></label>
                        <input asp-for="StartDate" class="form-control" readonly />
                    </div>
                    <div class="form-group col-6">
                        <label asp-for="CategoryId" class="control-label"></label>
                        <input asp-for="@Model.Categories.Name" class="form-control" readonly />
                    </div>
                    <div class="form-group col-6">
                        <label asp-for="LocationId" class="control-label"></label>
                        <input asp-for="@Model.Locations.Name" class="form-control" readonly />
                    </div>
                    <div class="form-group col-6">
                        <label asp-for="AgeId" class="control-label"></label>
                        <input asp-for="@Model.Ages.Name" class="form-control" readonly />
                    </div>
                    <div class="form-group col-6">
                        <label asp-for="HairId" class="control-label"></label>
                        <input asp-for="@Model.Hairs.Name" class="form-control" readonly />
                    </div>
                    <div class="form-group col-6">
                        <label asp-for="GenderId" class="control-label"></label>
                        <input asp-for="@Model.Genders.Name" class="form-control" readonly />
                    </div>
                    <div class="form-group col-6">
                        <label asp-for="ReligionId" class="control-label"></label>
                        <input asp-for="@Model.Religions.Name" class="form-control" readonly />
                    </div>
                    <div class="form-group col-6">
                        <label asp-for="EducationId" class="control-label"></label>
                        <input asp-for="@Model.Educations.Name" class="form-control" readonly />
                    </div>
                    <div class="form-group col-6">
                        <label asp-for="HeightId" class="control-label"></label>
                        <input asp-for="@Model.Heights.Name" class="form-control" readonly />
                    </div>
                    <div class="form-group col-6">
                        <label asp-for="WeightId" class="control-label"></label>
                        <input asp-for="@Model.Weights.Name" class="form-control" readonly />
                    </div>
                </div>
            </div>
            <div class="form-group btn-group col-12 mt-1">
                <div class="col-4 mt-1">
                    <a class="btn btn-primary btn-block" asp-action="Edit" asp-route-id="@Model.Code">Edit</a>
                </div>
                <div class="col-4 mt-1">
                    <a class="btn btn-secondary btn-block" asp-action="Index" asp-route-pageSize="@TempData.Peek("PageSize")" asp-route-pageSize="@TempData.Peek("PageSize")" asp-route-pageIndex="@TempData.Peek("CurrentPage")">Back</a>
                </div>
                <div class="col-4 form-check mt-2">
                        <input asp-for="isClosed" disabled/>
                        <label class="font-weight-bold h5">@Html.DisplayNameFor(model => model.isClosed)</label>
                </div>
            </div>
        </form>
    </div>
</div>

TrikProjekt/Views/Case2/Index.cshtml
@model IEnumerable<TrikProjekt56.Models.Case>
@{
    ViewData["Title"] = "Index";
    SortModel sortModel = (SortModel)ViewData["sortModel"];
    SiteModel site = ViewBag.Site;
}

<div class="container-fluid mainSystemCollectionMobile mt-3 mb-2">
    <div class = "row">
        <div class="col-sm">
            <a class="btn ml-1" asp-area="" asp-controller="Case2" asp-action="Index" style="font-size: 20px;">Case</a>
            <a class="btn ml-1" asp-area="" asp-controller="Case" asp-action="ExportToCSV" style="font-size: 20px;">Export To CSV</a>
        </div>
        <div class="col-sm justify-content-end">
                <a asp-action="Create" class="btn" style="float: right; font-size: 20px;" >Create new</a>
        </div>
    </div>
</div>
<div class="container-fluid mainSystemCollectionMobile">
    <div class="row">
            <partial name="TopBar" model="@site" />
    </div>
    <div class = "row">
        <div class = "container-fluid m-0 p-0">
            <table class="table mainTableCollection shadowtable">
                <thead>
                    <tr>
                        <th style="width: 30%">
                            <i class="@sortModel.GetColumn("Code").SortIcon" arial-hidden="true"></i>
                            <a class="text-primary" asp-action="Index" asp-route-sortExpression="@sortModel.GetColumn("Code").SortExpression">
                                @Html.DisplayNameFor(model => model.Code)
                            </a>
                        </th style="width: 30%">
                        <th>
                            <i class="@sortModel.GetColumn("name").SortIcon" arial-hidden="true"></i>
                            <a class="text-primary" asp-action="Index" asp-route-sortExpression="@sortModel.GetColumn("name").SortExpression">
                                @Html.DisplayNameFor(model => model.Name)
                            </a>
                        </th>
                        <th class="text-primary" style="width: 40%">
                            Options
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model) {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Code)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Name)
                                </td>
                                <td>
                                    <div class="btn-group">
                                        <a asp-action="Edit" asp-route-id="@item.Code">
                                            <span class="btn btn-outline-secondary myButton">
                                                <i class="fa fa-edit" aria-hidden="true"></i>
                                            </span>
                                        </a>
                                        <a asp-action="Details" asp-route-id="@item.Code">
                                            <span class="btn btn-outline-secondary myButton">
                                                <i class="fa fa-eye" aria-hidden="true"></i>
                                            </span>
                                        </a>
                                        <a asp-action="Delete" asp-route-id="@item.Code">
                                            <span class="btn btn-outline-secondary myButton">
                                                <i class="fa fa-trash" aria-hidden="true"></i>
                                            </span>
                                        </a>
                                    </div>
                                </td>
                            </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="row" style="margin-bottom: 100px;">
            <partial name="BottomBar" model="@site" />
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationPartial");}
}