TrikProjekt/Controllers/AgeController.cs
namespace TrikProjekt56.Controllers
{
    [Authorize]
    public class AgeController : Controller
    {
        [AcceptVerbs("Get","Post")]
        public JsonResult IsNameExisting(string Name, int Id=0)
        {
            bool existing = _repo.IsExisting(Name, Id);
            if (existing)
                return Json(data: false);
            else
                return Json(data: true);
        }
        public IActionResult Index(string sortExpression = "", string SearchText = "", int pageIndex = 1, int pageSize = 5)
        {
            SortModel sortModel = new SortModel();
            sortModel.AddColumn("name");
            sortModel.AddColumn("description");
            sortModel.ApplySort(sortExpression);
            ViewData["sortModel"] = sortModel;
            ViewBag.SearchText = SearchText;
            Pagination<Age> items = _repo.GetItems(sortModel.SortedProperty, sortModel.SortedOrder, SearchText, pageIndex, pageSize);
            var site = new SiteModel(items.TotalRecords, pageIndex, pageSize);
            site.SortExpression = sortExpression;
            this.ViewBag.Site = site;
            TempData["CurrentPage"] = pageIndex;
            TempData["PageSize"] = pageSize;
            return View(items);
        }

        private readonly IAge _repo;

        public AgeController(IAge repo)
        {
            _repo = repo;
        }

        public IActionResult Create()
        {
            Age item = new Age();
            TempData.Keep();
            return View(item);
        }

        [HttpPost]
        public IActionResult Create(Age item)
        {
            int currentPage = 1;
            if (TempData["CurrentPage"] != null)
            {
                currentPage = (int)TempData["CurrentPage"];
            }
            int pageSize = 5;
            if (TempData["PageSize"] != null)
            {
                pageSize = (int)TempData["PageSize"];
            }
            bool myBool = false;
            string errMessage = "";
            try
            {
                if (item.Name.Length < 3 || item.Name == null)
                    errMessage = "Name must be at least 3 characters";
                if (_repo.IsExisting(item.Name) == true)
                    errMessage = "Name " + item.Name + " already exists in database";
                if (errMessage == "")
                {
                    item = _repo.Create(item);
                    myBool = true;
                }
            }
            catch (Exception exc)
            {
                errMessage += " " + exc.Message;
            }
            if (myBool == false)
            {
                TempData["ErrorMessage"] = errMessage;
                ModelState.AddModelError("", errMessage);
                return View(item);
            }
            else
            {
                TempData["SuccessMessage"] = item.Name + " created successfully!";
                return RedirectToAction(nameof(Index), new { pageIndex = currentPage, pageSize = pageSize });
            }
        }

        public IActionResult Details(int id)
        {
            Age item = _repo.GetItem(id);
            TempData.Keep();
            return View(item);
        }
        public IActionResult Edit(int id)
        {
            Age item = _repo.GetItem(id);
            TempData.Keep();
            return View(item);
        }

        [HttpPost]
        public IActionResult Edit(Age item)
        {
            int pageSize = 5;
            if (TempData["PageSize"] != null)
            {
                pageSize = (int)TempData["PageSize"];
            }
            bool myBool = false;
            string errMessage = "";
            try
            {
                if (item.Name.Length < 3 || item.Name == null)
                    errMessage = "Name must be at least 3 characters";
                if (_repo.IsExisting(item.Name, item.Id) == true)
                    errMessage += item.Name + " already exists in database";
                if (errMessage == "")
                {
                    item = _repo.Edit(item);
                    TempData["SuccessMessage"] = item.Name + " saved successfully!";
                    myBool = true;
                }
            }
            catch (Exception exc)
            {
                errMessage += " " + exc.Message;
            }
            int currentPage = 1;
            if (TempData["CurrentPage"] != null)
            {
                currentPage = (int)TempData["CurrentPage"];
            }
            if (myBool == false)
            {
                TempData["ErrorMessage"] = errMessage;
                ModelState.AddModelError("", errMessage);
                return View(item);
            }
            else
            {
                return RedirectToAction(nameof(Index), new { pageIndex = currentPage, pageSize = pageSize });
            }
        }

        public IActionResult Delete(int id)
        {
            Age item = _repo.GetItem(id);
            TempData.Keep();
            return View(item);
        }

        [HttpPost]
        public IActionResult Delete(Age item)
        {
            int pageSize = 5;
            if (TempData["PageSize"] != null)
            {
                pageSize = (int)TempData["PageSize"];
            }
            bool myBool = false;
            string errMessage = "";
            try
            {
                if (errMessage == "")
                {
                    item = _repo.Delete(item);
                    TempData["SuccessMessage"] = "Deleted successfully!";
                    myBool = true;
                }
            }
            catch (Exception exc)
            {
                errMessage += " " + exc.Message;
            }
            int currentPage = 1;
            if (TempData["CurrentPage"] != null)
            {
                currentPage = (int)TempData["CurrentPage"];
            }
            if (myBool == false)
            {
                TempData["ErrorMessage"] = errMessage;
                ModelState.AddModelError("", errMessage);
                return View(item);
            }
            else
            {
                return RedirectToAction(nameof(Index), new { pageIndex = currentPage, pageSize = pageSize });
            }
        }
    }
}

TrikProjekt/Controllers/BlobController.cs
using System.IO;
using Microsoft.Azure.CognitiveServices.Vision.ComputerVision;
using Microsoft.Azure.CognitiveServices.Vision.ComputerVision.Models;
namespace TrikProjekt56.Controllers
{
    // Source
    // https://docs.microsoft.com/pl-pl/samples/azure-samples/storage-blobs-dotnet-webapp/net-photo-gallery-web-application-sample-with-azure-blob-storage/
    public class BlobController : Controller
    {
        const string blobContainerName = "webappstoragedotnet-imagecontainer";
        static BlobContainerClient blobContainer;
        public async Task<ActionResult> Index()
        {
            try
            {
                BlobServiceClient blobServiceClient = new BlobServiceClient("DefaultEndpointsProtocol=https;AccountName=triknewblob;AccountKey=8dUYz4i9NIz0DzQY5XbBDEUFFAKGy5rOJIFMJyhP8xKZ3j0w63g/C/nDJSh/l73hCopTRzU/m/cf+AStY5v63A==;EndpointSuffix=core.windows.net");
                blobContainer = blobServiceClient.GetBlobContainerClient(blobContainerName);
                await blobContainer.CreateIfNotExistsAsync(PublicAccessType.Blob);
                List<Uri> allBlobs = new List<Uri>();
                List<string> captions = new List<string>();
                foreach (BlobItem blob in blobContainer.GetBlobs())
                {
                    if (blob.Properties.BlobType == BlobType.Block)
                    {
                        BlobClient blobClient = blobContainer.GetBlobClient(blob.Name);
                        BlobProperties properties = await blobClient.GetPropertiesAsync();
                        foreach (var metadataItem in properties.Metadata)
                        {
                            captions.Add(metadataItem.Value.ToString());
                        }
                        allBlobs.Add(blobClient.Uri);
                    }
                }
                ViewBag.Captions = captions;
                return View(allBlobs);
            }
            catch (Exception ex)
            {
                ViewData["message"] = ex.Message;
                ViewData["trace"] = ex.StackTrace;
                return View("Error");
            }
        }

        [HttpPost]
        public async Task<ActionResult> UploadAsync()
        {
            ComputerVisionClient vision = new ComputerVisionClient(new ApiKeyServiceClientCredentials("1acfdcf3a3a2478584833e9082a25bf8"), new System.Net.Http.DelegatingHandler[] { });
            vision.Endpoint = "https://cvtrik.cognitiveservices.azure.com/";
            try
            {
                var request = await HttpContext.Request.ReadFormAsync();
                if (request.Files == null)
                    { return BadRequest("Could not upload, files are null!"); }
                var files = request.Files;
                if (files.Count == 0)
                    { return BadRequest("Empty files!"); }
                for (int i = 0; i < files.Count; i++)
                    {
                        var blob = blobContainer.GetBlobClient(GetRandomBlobName(files[i].FileName));
                        var stream = files[i].OpenReadStream();
                        blob.Upload(stream);
                        List<VisualFeatureTypes?> features = new List<VisualFeatureTypes?>() { VisualFeatureTypes.Description };
                        var result = await vision.AnalyzeImageAsync(blob.Uri.ToString(), features);
                        IDictionary<string, string> metadata = new Dictionary<string, string>();
                        metadata.Add("Caption", result.Description.Captions[0].Text);
                        await blob.SetMetadataAsync(metadata);
                }
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewData["message"] = ex.Message;
                ViewData["trace"] = ex.StackTrace;
                return View("Error");
            }
        }
        [HttpPost]
        public async Task<ActionResult> DeleteImage(string name)
        {
            try
            {
                Uri uri = new Uri(name);
                string filename = Path.GetFileName(uri.LocalPath);
                var blob = blobContainer.GetBlobClient(filename);
                await blob.DeleteIfExistsAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewData["message"] = ex.Message;
                ViewData["trace"] = ex.StackTrace;
                return View("Error");
            }
        }

        private string GetRandomBlobName(string filename)
        {
            string ext = Path.GetExtension(filename);
            return string.Format("{0:10}_{1}{2}", DateTime.Now.Ticks, Guid.NewGuid(), ext);
        }
    }
}

TrikProjekt/Controllers/HairController.cs
namespace TrikProjekt56.Controllers
{
    [Authorize]
    public class HairController : Controller
    {
        public JsonResult IsNameExisting(string Name, int Id = 0)
        {
            bool existing = _repo.IsExisting(Name, Id);
            if (existing)
                return Json(data: false);
            else
                return Json(data: true);
        }
      
        public IActionResult Index(string sortExpression = "", string SearchText = "", int pageIndex = 1, int pageSize = 5)
        {
            SortModel sortModel = new SortModel();
            sortModel.AddColumn("name");
            sortModel.AddColumn("description");
            sortModel.ApplySort(sortExpression);
            ViewData["sortModel"] = sortModel;
            ViewBag.SearchText = SearchText;
            Pagination<Hair> items = _repo.GetItems(sortModel.SortedProperty, sortModel.SortedOrder, SearchText, pageIndex, pageSize);
            var site = new SiteModel(items.TotalRecords, pageIndex, pageSize);
            site.SortExpression = sortExpression;
            this.ViewBag.Site = site;
            TempData["CurrentPage"] = pageIndex;
            TempData["PageSize"] = pageSize;
            return View(items);
        }

        private readonly IHair _repo;

        public HairController(IHair repo)
        {
            _repo = repo;
        }

        public IActionResult Create()
        {
            Hair item = new Hair();
            TempData.Keep();
            return View(item);
        }

        [HttpPost]
        public IActionResult Create(Hair item)
        {
            int currentPage = 1;
            if (TempData["CurrentPage"] != null)
            {
                currentPage = (int)TempData["CurrentPage"];
            }
            int pageSize = 5;
            if (TempData["PageSize"] != null)
            {
                pageSize = (int)TempData["PageSize"];
            }
            bool myBool = false;
            string errMessage = "";
            try
            {
                if (item.Name.Length < 3 || item.Name == null)
                    errMessage = "Name must be at least 3 characters";
                if (_repo.IsExisting(item.Name) == true)
                    errMessage = "Name " + item.Name + " already exists in database";
                if (errMessage == "")
                {
                    item = _repo.Create(item);
                    myBool = true;
                }
            }
            catch (Exception exc)
            {
                errMessage += " " + exc.Message;
            }
            if (myBool == false)
            {
                TempData["ErrorMessage"] = errMessage;
                ModelState.AddModelError("", errMessage);
                return View(item);
            }
            else
            {
                TempData["SuccessMessage"] = item.Name + " created successfully!";
                return RedirectToAction(nameof(Index), new { pageIndex = currentPage, pageSize = pageSize });
            }
        }

        public IActionResult Details(int id)
        {
            Hair item = _repo.GetItem(id);
            TempData.Keep();
            return View(item);
        }
        public IActionResult Edit(int id)
        {
            Hair item = _repo.GetItem(id);
            TempData.Keep();
            return View(item);
        }

        [HttpPost]
        public IActionResult Edit(Hair item)
        {
            int pageSize = 5;
            if (TempData["PageSize"] != null)
            {
                pageSize = (int)TempData["PageSize"];
            }
            bool myBool = false;
            string errMessage = "";
            try
            {
                if (item.Name.Length < 3 || item.Name == null)
                    errMessage = "Name must be at least 3 characters";
                if (_repo.IsExisting(item.Name, item.Id) == true)
                    errMessage += item.Name + " already exists in database";
                if (errMessage == "")
                {
                    item = _repo.Edit(item);
                    TempData["SuccessMessage"] = item.Name + " saved successfully!";
                    myBool = true;
                }
            }
            catch (Exception exc)
            {
                errMessage += " " + exc.Message;
            }
            int currentPage = 1;
            if (TempData["CurrentPage"] != null)
            {
                currentPage = (int)TempData["CurrentPage"];
            }
            if (myBool == false)
            {
                TempData["ErrorMessage"] = errMessage;
                ModelState.AddModelError("", errMessage);
                return View(item);
            }
            else
            {
                return RedirectToAction(nameof(Index), new { pageIndex = currentPage, pageSize = pageSize });
            }
        }

        public IActionResult Delete(int id)
        {
            Hair item = _repo.GetItem(id);
            TempData.Keep();
            return View(item);
        }

        [HttpPost]
        public IActionResult Delete(Hair item)
        {
            int pageSize = 5;
            if (TempData["PageSize"] != null)
            {
                pageSize = (int)TempData["PageSize"];
            }
            bool myBool = false;
            string errMessage = "";
            try
            {
                if (errMessage == "")
                {
                    item = _repo.Delete(item);
                    TempData["SuccessMessage"] = "Deleted successfully!";
                    myBool = true;
                }
            }
            catch (Exception exc)
            {
                errMessage += " " + exc.Message;
            }
            int currentPage = 1;
            if (TempData["CurrentPage"] != null)
            {
                currentPage = (int)TempData["CurrentPage"];
            }
            if (myBool == false)
            {
                TempData["ErrorMessage"] = errMessage;
                ModelState.AddModelError("", errMessage);
                return View(item);
            }
            else
            {
                return RedirectToAction(nameof(Index), new { pageIndex = currentPage, pageSize = pageSize });
            }
        }
    }
}

TrikProjekt/Views/Shared/BottomBar.cshtml
@model SiteModel
<div class = "container-fluid m-0 p-0 btn-group bottomBar">
    <div class="col-4 btn-group p-1 m-1">
        <p class="bottomtext">
            Showing @Model.StartRecord to @Model.EndRecord of @Model.Items Rows
        </p>
    </div>
    <div class="col-2 btn-group p-1 m-1 justify-content-center">
        <p class="bottomtext">
                <select class="form-control" id="pageSelector" style="margin-top:-5px !important;" asp-items="Model.GetPageSizes()"
                    onchange = "ChangePageSize(this)";>
                </select>
        </p>
    </div>
    <div class="col-4 btn-group p-1 m-1 justify-content-end">
        <p class="bottomtext">
            Showing @Model.CurrentPage / @Model.TotalPages Pages
        </p>
    </div>
</div>
<script>
    function ChangePageSize(obj)
    {
        var controllerName = '@this.ViewContext.RouteData.Values["controller"].ToString()';
        window.location.href = "/" + controllerName + '/@Model.Action' + "?pageSize=" + obj.value + "&SearchText@Model.SearchText" + "&sortExpression=" + "@Model.SortExpression";
    }
</script>

TrikProjekt/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=5.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="TrikProjekt56">
    <meta name="author" content="TrikTeam">
    <title>@ViewData["Title"] - TrikProjekt56</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/plugins/themefisher-font/style.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/plugins/bootstrap/bootstrap.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/plugins/animate-css/animate.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/plugins/magnific-popup/dist/magnific-popup.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/plugins/slick-carousel/slick.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/plugins/slick-carousel/slick-theme.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
</head>
<body id="home" data-spy="scroll" data-target=".navbar-nav" data-offset="80">
    <!--Start Preloader====================================-->
    <div class="preloader">
        <div class="sk-cube-grid">
            <div class="sk-cube sk-cube1"></div>
            <div class="sk-cube sk-cube2"></div>
            <div class="sk-cube sk-cube3"></div>
            <div class="sk-cube sk-cube4"></div>
            <div class="sk-cube sk-cube5"></div>
            <div class="sk-cube sk-cube6"></div>
            <div class="sk-cube sk-cube7"></div>
            <div class="sk-cube sk-cube8"></div>
            <div class="sk-cube sk-cube9"></div>
        </div>
    </div>
    <!-- End Preloader====================================-->
    <!-- Navigation=======================================-->
    <header id="navigation" class="navigation">
        <div class="container">
            <div class="navbar-header w-100">
                <nav class="navbar navbar-expand-lg navbar-dark px-0">
                    <!-- logo -->
                    <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index"><i class="fa-solid fa-3 fa-sm mr-1"></i><i class="fa-solid fa-k fa-sm mr-1"></i><i class="fa-solid fa-magic-wand-sparkles fa-sm mr-1"></i></a>
                    <!-- /logo -->
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar01"
                            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbar01">
                        <ul class="navbar-nav navigation-menu ml-auto">
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy"><i class="fa-solid fa-key fa-sm mr-1"></i>Privacy</a>
                            </li>
                            @if (SignInManager.IsSignedIn(User))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-white target" asp-area="" asp-controller="Case" asp-action="Index"><i class="fa-solid fa-list fa-sm mr-1"></i>Cases</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white target2" asp-area="" asp-controller="Case2" asp-action="Index"><i class="fa-solid fa-list fa-sm mr-1"></i>Cases - mobile</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="Case" asp-action="ShowCaseData"><i class="fa-solid fa-chart-pie fa-sm mr-1"></i>Statistics</a>
                                </li>
                                @if (Admins.admins.Contains(@UserManager.GetUserName(User)))
                                {
                                    <li class="dropdown nav-item">
                                    <a class="nav-link dropdown-toggle text-white" aria-expanded="true" aria-haspopup="true" data-toggle="dropdown">
                                    <i class="fa-brands fa-buffer fa-sm mr-1"></i>Modules
                                    </a>
                                        <ul class="dropdown-menu">
                                            <li class="nav-item">
                                                <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Categories</a>
                                            </li>
                                            <li class="nav-item">
                                                <a class="nav-link text-dark" asp-area="" asp-controller="Location" asp-action="Index">Locations</a>
                                            </li>
                                            <li class="nav-item">
                                                <a class="nav-link text-dark" asp-area="" asp-controller="Age" asp-action="Index">Age</a>
                                            </li>
                                            <li class="nav-item">
                                                <a class="nav-link text-dark" asp-area="" asp-controller="Hair" asp-action="Index">Hair</a>
                                            </li>
                                            <li class="nav-item">
                                                <a class="nav-link text-dark" asp-area="" asp-controller="Gender" asp-action="Index">Gender</a>
                                            </li>
                                            <li class="nav-item">
                                                <a class="nav-link text-dark" asp-area="" asp-controller="Religion" asp-action="Index">Religion</a>
                                            </li>
                                            <li class="nav-item">
                                                <a class="nav-link text-dark" asp-area="" asp-controller="Education" asp-action="Index">Education</a>
                                            </li>
                                            <li class="nav-item">
                                               <a class="nav-link text-dark" asp-area="" asp-controller="Height" asp-action="Index">Height</a>
                                            </li>
                                            <li class="nav-item">
                                                <a class="nav-link text-dark" asp-area="" asp-controller="Weight" asp-action="Index">Weight</a>
                                            </li>
                                        </ul>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-white" href="https://trikpython.azurewebsites.net"><i class="fa-solid fa-share-nodes fa-sm mr-1"></i>Machine Learning</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-white" asp-area="" asp-controller="Blob" asp-action="Index"><i class="fa-solid fa-image fa-sm mr-1"></i>Images</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-white" asp-area="" asp-controller="Admins" asp-action="Index"><i class="fa-solid fa-lock fa-sm mr-1"></i>Admins</a>
                                    </li>
                                }
                            }
                            <partial name="_LoginPartial" />
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
    </header>
    <!-- End Navigation====================================-->
    <!-- Main==============================================-->
    <main role="main">
        <!--Dialog sukces-->
        <div id="mySuccess" class="modal fade text-width: 30%;" role="dialog">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h2>Info</h2>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div id="MySuccessBody" class="modal-body alert alert-success">
                        Success
                    </div>
                    <div class="modal-footer">
                        &nbsp;
                        <button type="button" class="btn-info" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
        <!--Dialog sukces end-->
        <!--Dialog error start-->
        <div id="myError" class="modal fade text-width:30%;" role="dialog">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h2>Error</h2>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div id="MyErrorBody" class="modal-body alert alert-danger">
                        Error
                    </div>
                    <div class="modal-footer">
                        &nbsp;
                        <button type="button" class="btn-info" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
        <!--Dialog error end-->
        @RenderBody()
    </main>
    <!-- End Main=========================================-->
    <!-- Footer===========================================-->
    <footer class="footer fixed-bottom text-white bg-one">
        <div class="container">
            <div class="row">
                <div class="col-6 text-center" style="line-height: 60px;">
                    <p class="">Copyright &copy; <script>document.write(new Date().getFullYear())</script> - 3KTeam V-1.0.5</p>
                </div>
                <div class="col-6 social-icon p-0">
                    <ul class="list-inline">
                        <li class="list-inline-item mt-2"><a href="https://facebook.com/"><i class="tf-ion-social-facebook"></i></a></li>
                        <li class="list-inline-item mt-2"><a href="https://google.com/"><i class="tf-ion-social-google"></i></a></li>
                        <li class="list-inline-item mt-2"><a href="https://github.com/BaCe21/Projekt_Inzynierski_NTwK"><i class="tf-ion-social-github"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>
    <!-- End footer=======================================-->
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/plugins/jquery/jquery.min.js" asp-append-version="true"></script>
    <script src="~/plugins/bootstrap/bootstrap.min.js" asp-append-version="true"></script>
    <script src="~/plugins/slick-carousel/slick.min.js" asp-append-version="true"></script>
    <script src="~/plugins/filterzr/jquery.filterizr.min.js" asp-append-version="true"></script>
    <script src="~/plugins/magnific-popup/dist/jquery.magnific-popup.min.js" asp-append-version="true"></script>
    <script src="~/plugins/wow/wow.min.js" asp-append-version="true"></script>
    <script src="~/js/script.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TrikProjekt/Views/Shared/_ValidationPartial.cshtml
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        var errmsg = "@TempData["ErrorMessage"]";
        if (errmsg)
            openErrorModal(errmsg);
        var msg = "@TempData["SuccessMessage"]";
        if (msg)
            openSuccessModal(msg);
    });
</script>